#! /bin/bash

hastmux=NO
hash tmux 2>/dev/null && hastmux=YES
if [[ $hastmux == "NO" ]]
then
    if [[ $(uname -s) == "Darwin" ]]
    then
        brew install tmux
    elif [[ $(uname -s) == "Linux" ]]
    then
        sudo apt update
        sudo apt install -y git automake build-essential pkg-config libevent-dev libncurses5-dev

        cd /tmp
        wget https://github.com/tmux/tmux/releases/download/2.7/tmux-2.7.tar.gz
        tar xf tmux-2.7.tar.gz && cd tmux-2.7
        ./configure && make

        sudo make install
        cd - && rm -fr /tmp/tmux-2.7 /tmp/tmux-2.7.tar.gz
    fi
fi

if [[ ! -e ~/.tmux ]]
then
    git clone https://github.com/ikey4u/tmux.git ~/.tmux
    ls ~/.tmux.conf  2>/dev/null && rm ~/.tmux.conf
    ln -s ~/.tmux/tmuxrc ~/.tmux.conf
    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

exec $SHELL
