#! /bin/bash

if [[ ! -e ~/.tmux ]]
then
    git clone https://github.com/ikey4u/tmux.git ~/.tmux
    ls ~/.tmux.conf  2>/dev/null && rm ~/.tmux.conf
    ln -s ~/.tmux/tmuxrc ~/.tmux.conf
    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

exec $SHELL
