#! /bin/bash

sudo apt update
sudo apt install -y git automake build-essential pkg-config libevent-dev libncurses5-dev

cd /tmp
wget https://github.com/tmux/tmux/releases/download/2.7/tmux-2.7.tar.gz
tar xf tmux-2.7.tar.gz && cd tmux-2.7
./configure && make

sudo make install
cd - && rm -fr /tmp/tmux-2.7 /tmp/tmux-2.7.tar.gz
